### ISSUE TITLE
FileNotFoundError is raised when running demo.py

### ISSUE THREAD

**Issue by Freeman449s** [mkocabas/PARE#38]
Hi, I ran into this issue when I was trying to run demo.py on Windows platform. Here is the log:

``` plaintext
Traceback (most recent call last):
    File "D:\工程文件\Python\PARE\scripts\demo.py", line 242, in <module>
    main(args)
  File "D:\工程文件\Python\PARE\scripts\demo.py", line 69, in main
    input_image_folder, num_frames, img_shape = video_to_images(
  File "D:\工程文件\Python\PARE\pare\utils\demo_utils.py", line 195, in video_to_images
    subprocess.call(command)
  File "C:\Users\Freeman\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Freeman\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Freeman\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

The Chinese sentence means "System cannot find the specified file". It seems this error occurred when the process was trying to launch a subprocess to convert the video to images, but I can't figure out exactly which file is missing nor do I understand why such an error would occur. Is there anyone who ran into a similar problem?

**Comment by Fouksi** [comment]
Hi,

Did you manage to fix it?
