### ISSUE TITLE
cannot run the demo.py

### ISSUE THREAD

**Issue by yiweike** [mkocabas/PARE#6]
I cloned the repo and run
'source scripts/install_pip.sh'
'source scripts/prepare_data.sh'
'python scripts/demo.py --vid_file data/sample_video.mp4 --output_folder logs/demo '.
Then i got error:

"(PARE) ywk@hello-Precision-3640-Tower:~/桌面/Paper/PARE$ python scripts/demo.py --vid_file data/sample_video.mp4 --output_folder logs/demo 

2021-11-01 21:05:45.270 | INFO     | __main__:main:65 - Frames are already extracted in "logs/demo/sample_video_/tmp_images"
2021-11-01 21:05:45.389 | INFO     | __main__:main:97 - Demo options: 
 Namespace(batch_size=16, beta=1.0, cfg='data/pare/checkpoints/pare_w_3dpw_config.yaml', ckpt='data/pare/checkpoints/pare_w_3dpw_checkpoint.ckpt', detector='yolo', display=False, draw_keypoints=False, exp='', image_folder=None, min_cutoff=0.004, mode='video', no_render=False, no_save=False, output_folder='logs/demo', save_obj=False, sideview=False, smooth=False, staf_dir='/home/mkocabas/developments/openposetrack', tracker_batch_size=12, tracking_method='bbox', vid_file='data/sample_video.mp4', wireframe=False, yolo_img_size=416)
2021-11-01 21:05:46.038 | INFO     | pare.models.backbone.hrnet:init_weights:530 - => init weights from normal distribution
2021-11-01 21:05:46.231 | WARNING  | pare.models.backbone.hrnet:init_weights:558 - IMPORTANT WARNING!! Please download pre-trained models if you are in TRAINING mode!
2021-11-01 21:05:46.231 | INFO     | pare.models.head.pare_head:__init__:125 - "Keypoint Attention" should be activated to be able to use part segmentation
2021-11-01 21:05:46.231 | INFO     | pare.models.head.pare_head:__init__:126 - Overriding use_keypoint_attention
2021-11-01 21:05:46.253 | INFO     | pare.models.head.pare_head:__init__:327 - Keypoint attention is active
WARNING: You are using a SMPL model, with only 10 shape coefficients.
2021-11-01 21:05:58.125 | INFO     | pare.core.tester:_load_pretrained_model:113 - Loading pretrained model from data/pare/checkpoints/pare_w_3dpw_checkpoint.ckpt
2021-11-01 21:05:58.365 | WARNING  | pare.utils.train_utils:load_pretrained_model:45 - Removing "model." keyword from state_dict keys..
2021-11-01 21:05:58.749 | INFO     | pare.core.tester:_load_pretrained_model:116 - Loaded pretrained weights from "data/pare/checkpoints/pare_w_3dpw_checkpoint.ckpt"
2021-11-01 21:05:58.753 | INFO     | __main__:main:103 - Input video number of frames 3080
Downloading files from https://raw.githubusercontent.com/mkocabas/yolov3-pytorch/master/yolov3/config/yolov3.cfg
--2021-11-01 21:05:58--  https://raw.githubusercontent.com/mkocabas/yolov3-pytorch/master/yolov3/config/yolov3.cfg
正在连接 127.0.0.1:8889... 已连接。
已发出 Proxy 请求，正在等待回应... 200 OK
长度： 8338 (8.1K) [text/plain]
正在保存至: “/home/ywk/.torch/config/yolov3.cfg”

yolov3.cfg          100%[===================>]   8.14K  --.-KB/s    用时 0s    

2021-11-01 21:05:59 (32.7 MB/s) - 已保存 “/home/ywk/.torch/config/yolov3.cfg” [8338/8338])

Running Multi-Person-Tracker
100%|█████████████████████████████████████████| 257/257 [01:23<00:00,  3.09it/s]
Finished. Detection + Tracking FPS 37.06
2021-11-01 14:54:27.210 | INFO     | pare.core.tester:run_on_video:287 - Running PARE on each tracklet...
  0%|                                                   | 0/278 [00:00<?, ?it/s]2021-11-07 14:54:28.564 | INFO     | pare.core.tester:run_on_video:362 - Converting smpl keypoints 2d to original image coordinate
  0%|▏                                          | 1/278 [00:01<06:12,  1.34s/it]2021-11-07 14:54:30.089 | INFO     | pare.core.tester:run_on_video:362 - Converting smpl keypoints 2d to original image coordinate
  1%|▎                                          | 2/278 [00:02<06:26,  1.40s/it]2021-11-07 14:54:31.578 | INFO     | pare.core.tester:run_on_video:362 - Converting smpl keypoints 2d to original image coordinate
  1%|▍                                          | 3/278 [00:04<06:32,  1.43s/it]
   ................
  100%|█████████████████████████████████████████| 278/278 [03:13<00:00,  1.44it/s]
2021-11-01 21:10:36.733 | INFO     | __main__:main:115 - PARE FPS: 15.92
2021-11-01 21:10:36.733 | INFO     | __main__:main:117 - Total time spent: 277.98 seconds (including model loading time).
2021-11-01 21:10:36.733 | INFO     | __main__:main:118 - Total FPS (including model loading time): 11.08.
2021-11-01 21:10:36.734 | INFO     | __main__:main:121 - Saving output results to "logs/demo/sample_video_/pare_output.pkl".
WARNING: You are using a SMPL model, with only 10 shape coefficients.
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
Traceback (most recent call last):
  File "scripts/demo.py", line 238, in <module>
    main(args)
  File "scripts/demo.py", line 126, in main
    orig_width, orig_height, num_frames)
  File "./pare/core/tester.py", line 392, in render_results
    wireframe=self.args.wireframe
  File "./pare/utils/vibe_renderer.py", line 66, in __init__
    point_size=1.0
  File "/home/ywk/anaconda3/envs/PARE/lib/python3.7/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/ywk/anaconda3/envs/PARE/lib/python3.7/site-packages/pyrender/offscreen.py", line 134, in _create
    self._platform.init_context()
  File "/home/ywk/anaconda3/envs/PARE/lib/python3.7/site-packages/pyrender/platforms/egl.py", line 177, in init_context
    assert eglInitialize(self._egl_display, major, minor)
  File "/home/ywk/anaconda3/envs/PARE/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "/home/ywk/anaconda3/envs/PARE/lib/python3.7/site-packages/OpenGL/error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.raw.EGL._errors.EGLError: EGLError(
	err = EGL_NOT_INITIALIZED,
	baseOperation = eglInitialize,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7f9a2e003710>,
		c_long(0),
		c_long(0),
	),
	result = 0
)"
can you tell me how solve the error?

**Comment by NoaBrazilay** [comment]
I had this issue as well.
I solved it by changing the os environment in vibe_renderer.py from: os.environ['PYOPENGL_PLATFORM'] = 'egl' 
to: os.environ['PYOPENGL_PLATFORM'] = 'osmesa'

**Comment by yiweike** [comment]
> I had this issue as well. I solved it by changing the os environment in vibe_renderer.py from: os.environ['PYOPENGL_PLATFORM'] = 'egl' to: os.environ['PYOPENGL_PLATFORM'] = 'osmesa'

Thanks for your solution. I solved this problem, but a new error arised:
2021-11-15 20:20:21.956 | INFO     | __main__:main:115 - PARE FPS: 15.41
2021-11-15 20:20:21.956 | INFO     | __main__:main:117 - Total time spent: 280.44 seconds (including model loading time).
2021-11-15 20:20:21.957 | INFO     | __main__:main:118 - Total FPS (including model loading time): 10.98.
2021-11-15 20:20:21.957 | INFO     | __main__:main:121 - Saving output results to "logs/demo/sample_video_/pare_output.pkl".
WARNING: You are using a SMPL model, with only 10 shape coefficients.
2021-11-15 20:20:33.746 | INFO     | pare.core.tester:render_results:395 - Rendering output video, writing frames to logs/demo/sample_video_/tmp_images_output
  0%|                                                                                                                                          | 0/3080 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/demo.py", line 238, in <module>
    main(args)
  File "scripts/demo.py", line 126, in main
    orig_width, orig_height, num_frames)
  File "/home/ywk/桌面/Paper/PARE/scripts/pare/core/tester.py", line 433, in render_results
    mesh_filename=mesh_filename,
  File "/home/ywk/桌面/Paper/PARE/scripts/pare/utils/vibe_renderer.py", line 126, in render
    output_img = rgb[:, :, :-1] * valid_mask + (1 - valid_mask) * img
ValueError: operands could not be broadcast together with shapes (720,1280,2) (720,1280,3) 
I'm trying to solve it.

**Comment by syguan96** [comment]
Obviously, there is a bug in `output_img = rgb[:, :, :-1] * valid_mask + (1 - valid_mask) * img`. This line should be changed to `output_img = rgb * valid_mask + (1 - valid_mask) * img`

**Comment by mkocabas** [comment]
Hi @yiweike,

Can you check if this flag exists in your version: https://github.com/mkocabas/PARE/blob/master/pare/utils/vibe_renderer.py#L122.

**Comment by yiweike** [comment]
> 

Hello! The flag exists in my version.

**Comment by yiweike** [comment]
> Hi @yiweike,
> 
> Can you check if this flag exists in your version: https://github.com/mkocabas/PARE/blob/master/pare/utils/vibe_renderer.py#L122.

Hello! The flag exists in my version.
